### PR TITLE
Add support for customizable database types for transport_maps, recip…

### PR DESCRIPTION
**Pull request by tobias-richter**
…ient_canonical_maps, sender_canonical_maps

I introduced

* `postfix_sender_canonical_maps_database_type`
* `postfix_recipient_canonical_maps_database_type` and
* `postfix_transport_maps_database_type`

in order to be able to customize these database types in detail.

### CODE REVIEW

**Comment by tersmitten** [comment]
Looks like a nice addition. I think that you also need to make changes in `handlers/main.yml`. Can you have a look?

**Comment by tobias-richter** [comment]
@tersmitten you are totally right, I overlooked that part. This also explanes some strange issues I was experiencing.
This is now adjusted.

**Comment by tersmitten** [comment]
Also see #90

**Comment by tobias-richter** [comment]
Yes, I saw this PR just after I created mine. But there is no activity at the moment. Should I adjust my PR to also contain the changes from #90?

**Pull request merged**
