### PR TITLE
Make inet_interfaces configurable

### PR DESCRIPTION
**Pull request by md5**

### CODE REVIEW

**Comment by tersmitten** [comment]
@md5 Can you explain the last commit?

**Comment by md5** [comment]
@tersmitten When I run `vagrant up`, the Ansible provisioner fails since it can't find the `postfix` role. It's able to find the `ansible-postfix` role, however. I figured that change was fine since `tests/test.yml` also uses `ansible-postfix` (presumably for the same reason).

**Comment by md5** [comment]
All this assumes that the user's checkout is called `ansible-postfix`.

**Comment by tersmitten** [comment]
@md5 For me it just work fine. We use this for all our roles. Do you have the latest version of Vagrant and Virtualbox?

**Comment by tersmitten** [comment]
> All this assumes that the user's checkout is called ansible-postfix

That explains it. We always check it out as `postfix`. Can you please revert that particular change?

**Comment by md5** [comment]
@tersmitten I've dropped that commit.

What do you think about doing something to make `vagrant up` work out of the box? As far as I can tell, the `Vagrantfile` is only meant for testing, so it would be cool if it could work without being reliant on the directory name of the cloned repository.

**Comment by tersmitten** [comment]
I will figure it out

**Comment by md5** [comment]
Sounds good.

If you don't mind syncing a new tag to Ansible Galaxy once this is merged, that would be very helpful.

**Comment by tersmitten** [comment]
Done

**Comment by md5** [comment]
Thanks!

**Pull request merged**
